+++
draft = false
date="2010-07-15 00:21:09"
title="Drive - Dan Pink"
tag=['software-development']
category=['Software Development']
+++

One of the more interesting presentations doing the rounds on twitter and on our internal mailing lists is the following one by Dan Pink titled 'http://www.youtube.com/watch?v=u6XAPnuFjJc[Drive - The surprising truth about what motivates us]'.+++<object width="640" height="385">++++++<param name="movie" value="http://www.youtube.com/v/u6XAPnuFjJc&hl=en_US&fs=1">++++++</param>+++</param>+++<param name="allowFullScreen" value="true">++++++</param>+++</param>+++<param name="allowscriptaccess" value="always">++++++</param>+++</param>+++<embed src="http://www.youtube.com/v/u6XAPnuFjJc&hl=en_US&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="640" height="385">++++++</embed>+++</embed>+++</object>+++

This topic generally interests me anyway but it's quite intriguing that the research Dan has gathered support for what I imagine many people intrinsically knew.

== Incentives

The presentation dispels the myth that money always works as a motivator for getting people to do what we want them to do. Rather its value is more noticeable as an anti de-motivator - Pink suggests that *organisations need to pay people enough so that money is no longer an issue*.

He goes on to detail research which shows that money doesn't work as a motivator when a task requires even rudimentary cognitive skill which suggests it wouldn't be all that effective in a software development context.

Following on with this logic Pink suggests that before he did his research he would have thought that if you wanted to get innovation in an organisation then that would best be achieved by giving out an innovation bonus. He now suggests this wouldn't be effective.

We had an interesting example of this recently where the ThoughtWorks UK and Australia offices tried to run an http://www.facebook.com/ThoughtWorks#!/album.php?aid=19013&id=117154494974817[iPad App competition] with the prize of an iPad for the winning entry.

This worked fine in Australia but didn't at all in the UK. Since the 'incentive' was the same in both cases I'm inclined to believe that the reason it worked better in Australia was due to the fact that the guys there managed to create a spirit of competition between the Melbourne & Sydney offices and between the participants.

== How do we get better performance?

Pink suggests that there are three main factors which lead to better performance & personal satisfaction - *autonomy*, *mastery* and *purpose* - and I think that to an extent we can get all of these with the agile approach to software development.

== Autonomy

Pink suggests that people like to be self directed and direct their own lives and he gives the example of http://blogs.atlassian.com/developer/fedex/[Atlassian's Fedex days] as an example of developers being given the freedom to do whatever they want for 24 hours and coming up with some really useful products at the end of it.

I think we have autonomy to an extent on software projects. We might not have the ability to choose exactly what problem we're solving for our customer but we do mostly have the ability to choose how we're going to solve it.

We can choose how we're going to design the solution, discussing various trade offs with our customer if there's more than one way to solve it...

== Mastery

Pink points out that many people play musical instruments at the weekend even though they have little chance of ever earning money from doing so and he suggests that the reason for this is its fun and we have *an urge to get better*.

Software development is almost a perfect fit for mastery because *there are so many different areas for improvement no matter how good you are*.

Corey Haines has been pushing the idea of 'http://programmingtour.blogspot.com/2010/07/learn-to-type-week.html[Learn To Type Week]' which is just one example of this.

I thought I was pretty good at touch typing but after trying out the different exercises he's been linking to I realise that there are still areas in which I can improve upon and it's quite fun trying out the exercises and trying to get better.

Apart from that there are http://codekata.pragprog.com/[code katas], http://github.com/edgecase/ruby_koans[code koans], new languages and many other ways in which we can improve ourselves.

== Purpose

Pink describes purpose as "*what gets you up in the morning racing to go to work*" and suggests that we need something more than just making profit.

I mostly don't feel that I'm actually "going to work" on the projects I've been on because the majority of the time the other two factors are being met and I have the opportunity to work with passionate people who want to deliver high quality software together.

I'm not sure if that quite gets to the essence of purpose but it certainly doesn't feel that what I'm working on is pointless - we're building something which helps solve a problem for our customer and that seems like a valuable thing to do to me.

== Overall

I found this presentation really interesting and the way it's presented with the cartoons is really cool as well.

I haven't yet read Dan Pink's book 'http://www.amazon.com/Drive-Surprising-Truth-About-Motivates/dp/1594488843/ref=sr_1_1?ie=UTF8&s=books&qid=1279153152&sr=8-1[Drive]' which presumably expands upon this talk but I've read 'http://www.amazon.com/Whole-New-Mind-Right-Brainers-Future/dp/1594481717/ref=ntt_at_ep_dpt_2[A Whole New Mind]' which was interesting reading so I'm sure I'll read this one at some stage.
