+++
draft = false
date="2012-01-16 01:01:30"
title="Focused Retrospectives: things to watch for"
tag=['agile', 'retrospective']
category=['Agile']
+++

A few weeks ago a slide deck from an http://www.slideshare.net/estherderby/agile-retrospectives-4976896[Esther Derby presentation on retrospectives] was doing the rounds on twitter and one thing that I found interesting in the deck was the suggestion that a retrospective needs to be focused in some way.

I've participated in a few focused retrospectives over the past 7/8 months and I think there are some things to be careful about when we decide to focus on something specific rather than just looking back at a time period in general.

== Victimisation

In a retrospective about 6 months ago or so we focused on the analysis part of our process as we'd been struggling to know when a story was complete and what exactly its scope was.

The intention wasn't the victimise the people working in that role but since there were very few of them compared to people in other roles they were forced onto the defensive as people criticised their work.

It was a very awkward retrospective and it felt like a retrospective was probably the wrong place to address the problem.

It might have been better for the analysts to have been given the feedback privately and then perhaps worked on a solution with a smaller group of people.

== Looking for a problem when there isn't one

I had an interesting conversation with a colleague about whether with very focused retrospectives we end up looking for something to change rather than having any specific pain point which necessitates change.

The problem with this is that there's a thin line between following the status quo because it works and getting complacent and not looking for ways to improve.

It is interesting to keep in mind though that *if it doesn't seem like there is something to change in an area then perhaps that's the wrong thing to be focusing on at the moment*, which nicely leads into...

== Let the team choose the area of focus

There can be a tendency in the teams I've worked on for people in managementy roles to dictate what the focus of the retrospective will be which makes sense in a way since they may be able to see something which the team can't.

On the other hand it can mean that we end up focusing on the wrong thing and team members probably won't be that engaged in the retrospective since they don't really get to dictate what's talked about.

Esther points this out out on slide 23 of the presentation - "*Choose a focus that reflects what's going on for the team*". This perhaps can be determined by having a vote before hand based on some topics that seem prominent.

== In summary

There's lots of other useful tips in Esther's slide deck which are worth having a look at and I'm sure most of the potential problems I've listed probably don't happen when we have a highly skilled/experienced facilitator.
