+++
draft = false
date="2010-06-21 21:30:20"
title="iPad: First thoughts"
tag=['ipad']
category=['Software Development']
+++

I've had the iPad for about a month now and since my colleagues http://martinfowler.com/bliki/iPad.html[Martin Fowler], http://memeagora.blogspot.com/2010/06/ipad-good-bad-and-ugly.html[Neal Ford] and http://skizz.biz/blog/2010/05/01/thoughts-on-the-ipad/[Chris Stevenson] have already previously written about their experiences with it I thought I'd share the way I'm using it as well.

== Twitter

I follow a lot of people involved in software development on twitter and come across a lot of interesting articles/blogs that people link to or write. A lot of the time I don't really want to read those posts when I come across them - it would be much better if I could just save them to read later on.

Before I had the iPad the way I did this was just by having loads of tabs open on Chrome which tended to result in my computer grinding to a halt because of the memory being consumed by having all those articles open.

On the iPad I've been making use of the http://www.osfoora.com/[Osfoora HD] twitter client which is integrated with http://www.instapaper.com/[Instapaper] - an application which allows you to save web pages and then read them offline.

I'm online most of the time so I was initially unsure how much value I'd get out of it. I now *read almost every technical article I come across via Instapaper*.

I've been posting to twitter way more because it's now so easy to post links there which is the main way that I use it.

== Reading technical material

Before I bought the iPad I wanted to make sure that I'd be able to read pdfs on it. I have a lot of technical books as pdfs and I've wanted to buy a device that would allow me to read those more easily since I don't like reading pdfs on my laptop unless they're purely coding books.

Luckily the http://www.goodiware.com/goodreader.html[Good Reader] application allows me to do exactly that and the ability to crop the pages to be exactly how you want is fantastic and something that I'd never even thought of until I saw it.

I use Google Reader for my RSS feeds so none of the RSS reader applications really appealed to me until I came across http://reederapp.com/[reeder] which basically sits on top of Google Reader and downloads all the unread items for offline viewing.

It's integrated with twitter as well so I can easily post any interesting things that I read.

== Blogging

I'm using the http://blogpress.coollittlethings.com/[Blog Press] application which I've found to be better than the Word Press one because it allows me to cut and paste text around the post - I found that I couldn't do this with the Word Press application.

Ben Parr has a more extensive post on http://mashable.com/2010/04/03/can-you-blog-from-an-ipad/[his experiences blogging from the iPad] but overall for me it's still not as good as blogging from http://www.red-sweater.com/marsedit/[Mars Edit] on the Mac.

It's a bit of a hassle copying links into posts because you need to manually write the Html to do so which is pretty painful in itself but also because you have to keep switching to other applications to get the links in the first place.

I have been using BlogPress to quickly copy/paste any interesting quotes from the blogs that I read but more often than not I end up posting it as a draft and then tidying it up with Mars Edit later on.

== Videos

Watching videos on the iPad is amazing - the picture is obviously much bigger than it would be on an iPhone and it's much more convenient than it would be on a laptop.

I watch technical videos now and then for which the http://www.inmethod.com/air-video/index.html[Air Video] application comes in really handy. It can convert any video files you have on your computer to a format that can be watched on the iPad although there are several formats which work without conversion as well.

http://www.infoq.com/[InfoQ] and http://skillsmatter.com/[Skills Matter] both frequently post technical presentations and this week http://search.twitter.com/search?q=ndc2010[NDC 2010] has made a lot of the presentations from that conference available to download.
