+++
draft = false
date="2016-06-19 07:22:57"
title="Unix: Split string using separator"
tag=['unix']
category=['Shell Scripting']
+++

I recently found myself needing to iterate over a bunch of '/' separated strings on the command line and extract just the text after the last '/'.

e.g. an example of one of the strings

[source,text]
----

A/B/C
----

I wanted to write some code that could split on '/' and then pick the 3rd item in the resulting collection.

One way of doing this is to echo the string and then pipe it through cut:

[source,bash]
----

$ string="A/B/C"
$ echo ${string} | cut -d"/" -f3
C
----

or awk:

[source,bash]
----

$ echo ${string} | awk -F"/" '{ print $3}'
C
----

I don't like having to echo the string - it feels a bit odd so I wanted to see if there was a way to do the parsing more 'inline'.

I came across http://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash[this post] which explains how to change the internal field separator (IFS) on the shell and then parse the string into an array using http://ss64.com/bash/read.html[read]. I gave it a try:

[source,bash]
----

$ IFS="/" read -ra ADDR <<< "${string}"; echo ${ADDR[2]}
C
----

Works! We can even refer to the last item in the array using -1 instead of it's absolute position:

[source,bash]
----

$ IFS="/" read -ra ADDR <<< "${string}"; echo ${ADDR[-1]}
C
----

I'd not come across this use of the 'read' function before. The key is the '-a' parameter. From the man page:

____
-a aname The words are assigned to sequential indices of the array variable aname, starting at 0. All elements are removed from aname before the assignment. Other name arguments are ignored.
____

So we're resetting the internal field separator and then reading the string into another variable as an array split on the '/' character.

Pretty neat although now it's longer than the original command and I'm sure I'll forget the syntax.

Further down the page is another suggestion which seems even harder to remember but is much shorter:

[source,bash]
----

$ echo ${string##*/}
C
----

This drops from the beginning of the string up until the last occurrence of '/' which is exactly what we want.

This way is the nicest and doesn't require any echoing if we just want to assign the result to a variable. The echo is only used here to see the output.
