+++
draft = false
date="2011-02-26 04:39:19"
title="Pecha Kucha: My first attempt"
tag=['communication']
category=['Communication']
+++

The first time I came across the http://www.pecha-kucha.org/[Pecha Kucha] style of presenting was at the XP 2010 conference during the http://multimedie.adm.ntnu.no/mediasite/SilverlightPlayer/Default.aspx?peid=2cb930a5b6444cf8afd7fcd96b7b0c61[Agile Suitcase] session where http://www.thekua.com/atwork/[Pat Kua] and some others talked about http://xp2010.org/program?sid=26&o=7[the practices, principles and values they most favoured].

I've never done one before but as part of the preparation work for http://www.thoughtworks.com/thoughtworks-university[ThoughtWorks University] each of the trainers had to prepare one which we then presented to each other yesterday.

Despite the format being different than a normal presentation I still think the general idea of presenting any information applies - *if you can tell it as a story then you have a much greater chance of keeping people's attention*.

This was advice that I first got from http://erik.doernenburg.com/[Erik Doernenburg] almost 2 years ago when I was preparing to give an http://www.markhneedham.com/blog/2009/06/30/f-what-ive-learnt-so-far/[F# presentation].

I guess everyone has their theories and guidelines of what makes a good presentation but for me the underlying idea is that *it has to be fun for me to present*.

If it isn't then it's going to be really difficult for it to be fun to listen to.

These were some of the things I learnt from the whole process:

== Preparation

* I generally don't like rehearsing exactly what I'm going to say because I think it makes the presentation a bit less fresh when you actually do it. In this case however you need to have a reasonably good idea of how much you can talk in 20 seconds so it makes more sense.
* A side effect of doing this was that I realised how much I had originally planned to cram into some of the slides and was therefore able to split some of the narrative out onto another slide.
* Most of the ideas around slide design came from the http://www.slideshare.net/sumeet.moghe/tips-for-effective-presentations-4462308[Presentation Zen presentation] that http://www.learninggeneralist.com/[Sumeet] gave us earlier in the week. I haven't read the book but from what I've heard it seems to give some pretty good ideas for making slides engaging.

== Delivery

* I tend to improvise quite a bit when presenting so I often throw things in that I think of at the time. The problem with doing that in a Pecha Kucha is that it can ruin the timings that you've practiced beforehand!
* I *looked back at the slides way too much* which I only realised from watching the video that Sumeet had recorded. I think it's a bit of an instinct because in a lot of presentations I've done you want to point out something which is on the slide. In this style of presentation it was unnecessary.
* *People interpret images differently* - even with an audience of just 7 or 8 it was noticeable across the different presentations that some people understood or could relate to the images used by the presenter and some couldn't! I'm not sure exactly how you get around that problem.

Overall I think this is a really cool presentation style and one that I think should be used more often.

Someone actually suggested we should get the ThoughtWorks management to give their monthly update reports in this format which would certainly be fascinating to see.
