+++
draft = false
date="2010-12-27 19:15:51"
title="Vim: Learnings so far"
tag=['software-development', 'vim']
category=['Software Development']
+++

I've been using Vim instead of http://www.jetbrains.com/ruby/index.html[RubyMine] for the last month or so and it's been interesting observing the way that I browse code as I add plugins to make my life easier.

== Between files

I generally don't know exactly where in the folder structure different files live since I'm used to being able to search by just the name i.e. RubyMine's Ctrl-N

http://yehudakatz.com/2010/07/29/everyone-who-tried-to-convince-me-to-use-vim-was-wrong/[Yahuda Katz wrote a blog post] earlier in the year where he listed some of the plugins he's been using - one of which is called https://wincent.com/products/command-t[Command-T] and allows exactly this functionality.

I also quite like the ability to quickly access files that I've recently opened i.e. files which are in the Vim buffer or RubyMine's Ctrl-E. The http://www.vim.org/scripts/script.php?script_id=1984[FuzzyFinder] plugin provides that functionality.

I've also tagged all my Ruby gems and the source code of the project using http://ctags.sourceforge.net/[Exuberant CTags] which then allows http://blog.bojica.com/2010/06/27/ctags-and-vim-for-ruby-on-rails-development[easy browsing to methods/classes].

== Inside files

I've noticed that the way I browse inside files has changed since I started using Vim.

I used to just scroll around files using the mouse but now I find myself moving around a file by line numbers instead.

A lot of the commands for file editing in Vim are based on moving/changing/deleting to a particular symbol so you become almost a human parser when reading a line of text.

I found/am finding the following quite useful for learning Vim shortcuts:

* http://www.viemu.com/vi-vim-cheat-sheet.gif[Vim cheat sheet]
* http://tnerual.eriogerg.free.fr/vimqrc.pdf[Vim quick reference card]
* http://jmcpherson.org/editing.html[Efficient Editing with Vim]

When coding in Java/C# I rely quite heavily on auto complete to tell me what methods I have available to me on a certain object.

Although I don't use it that frequently the http://www.vim.org/scripts/script.php?script_id=182[SuperTab] plugin works reasonably well when you do need help.

http://twitter.com/#!/just3ws[Mike] pointed out https://github.com/spicycode/Vimlander-2-The-Quickening[Vimlander-2-The-Quickening] which has some of the plugins I mentioned and several others ready to use.
