+++
draft = false
date="2012-02-28 00:02:21"
title="Haskell: Getting the nth element in a list"
tag=['haskell']
category=['Haskell']
+++

I started trying to solve some of the http://projecteuler.net/problems[Project Euler problems] as a way to learn a bit of Haskell and http://projecteuler.net/problem=7[problem 7] is defined like so:

____
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?
____

I read that the http://en.wikipedia.org/wiki/Sieve_of_Eratosthenes[Sieve of Eratosthenes] is a useful algorithm for working out all the prime numbers and there's http://en.literateprograms.org/Sieve_of_Eratosthenes_(Haskell)#chunk use:primes_naive[a page on the Literate Programs wiki explaining how to derive them using it].

The most naive implementation of all the primes ends up reading like this:

[source,haskell]
----

primes = 2 : sieve [3,5..]  where
    sieve []     = []
    sieve (p:xs) = p : sieve (xs `minus` [p,p+2*p..])
----

That gives an infinite sequence of all the prime numbers but I wanted to be able to specifically pick the 10,001st prime number which I assumed would be named 'nth' or something like that.

As it turns out we actually need to use the '!!' operator which I found out from http://scienceblogs.com/goodmath/2009/11/writing_basic_functions_in_has.php[Mark Chu-Carroll's blog post]:

[source,haskell]
----

*Main> :t (!!)
(!!) :: [a] -> Int -> a
----

[source,haskell]
----

problem_7 = primes !! 10000 -- 0 indexed so we need to get the position one before 10,001
----

It takes a while to run but we end up with the answer:

[source,haskell]
----

*Main> problem_7
104743
----
