+++
draft = false
date="2009-03-14 01:28:04"
title="QCon London 2009: DDD & BDD - Dan North"
tag=['qconlondon', 'qcon', 'infoq', 'conferences']
category=['QCon']
+++

The second presentation in the http://qconlondon.com/london-2009/tracks/show_track.jsp?trackOID=228[Domain Driven Design track] at http://qconlondon.com/london-2009/[QCon] was titled 'http://qconlondon.com/london-2009/presentation/BDD+%26+DDD[DDD & BDD]' and was presented by my colleague http://dannorth.net/[Dan North] - a late stand in for Greg Young who apparently injured himself playing ice hockey.

Eric did http://www.infoq.com/interviews/Architecture-Eric-Evans-Interviews-Greg-Young[an interview with Greg at QCon San Francisco 2007] where Greg talks about some of his ideas and apparently there is an InfoQ video kicking around of Greg's 'Unshackle Your Domain' talk from QCon San Francisco 2008 which we were told to pester InfoQ to post on their website!

Anyway this one was Dan's talk about the relation between Domain Driven Design and Behaviour Driven Development.

The slides for the presentation are http://qconlondon.com/london-2009/file?path=/qcon-london-2009/slides/DanNorth_BDDDDD.pdf[here].

== What did I learn?

* Dan briefly covered some of the Domain Driven Design basics, including quoting http://jimmynilsson.com/blog/[Jimmy Nilsson] on what it actually is:
+
____
Focus on the domain and letting it affect the software very much
____
+
A fairly succinct way of summing up the book in one sentence I think!

* Dan described the *core domain* as being your differentiator (what makes you special), the thing the stakeholders care most about, *the place where the most interesting conversations are going to be*, the richest seams for knowledge crunching. I don't think I really understood what the core domain was before watching this presentation - it also helped me make sense of Eric Evans' comment in the http://www.markhneedham.com/blog/2009/03/13/qcon-london-2009-what-ive-learned-about-ddd-since-the-book-eric-evans/[previous talk] where he spoke of *not spreading the modeling too thin*, instead keep it focused on the areas that provide you most value.
* He spoke of the *benefits of having a shared language* used by everyone on your team - you don't have the translation effort which is very tiring! Driving the language into everything has the added benefit of giving you a place to put behaviour, otherwise it ends up spread all over the place. Dan spoke of the *ubiquitous language only being consistent within a bounded context* - not really so ubiquitous after all!
* Next up was the other side of the coin - http://behaviour-driven.org/[Behaviour Driven Development]. He described BDD as '*focusing on the behaviour of an application from the point of view of its stakeholders*', where the stakeholders are anyone who cares about the application. BDD is about outside-in development where requirements are expressed as stories which have acceptance criteria to help us know when we're 'done'. The acceptance criteria are comprised of scenarios made up of steps and these then become acceptance tests when they are completed. He also riffed a bit about http://sirenian.livejournal.com/42871.html[bug driven development] - outside in taken to the extreme. Dan made an interesting point that BDD is about a mindset rather than the tools and I think I agree there - I've not used the tools much but I try to consider the behaviour I'm trying to drive whenever I'm writing tests/examples.
* For a while I've preferred to describe the way I write code as being driven by example rather than driven by tests but it is still referred to as TDD - Dan helped me to see how this makes sense. We *code by example to implement features but when those examples are done then they act as tests*.
* Dan spoke of the '*Glaze Effect*' when speaking with domain experts i.e. when you talk using language from a domain they don't understand - probably using language that is too technical for them to care.
* Dan said the first part of the book is effectively 'The Hobbit' but the really interesting stuff only comes in 'The Lord of the Rings' which is the second part. That's pretty much my experience as well - I gained way more from reading the second half than the first half. Dan pointed out that the ideas *around scaling DDD are applicable anywhere* - they're not specific just to DDD.
* BDD is about conversations in the ubiquitous language to produce software while DDD is about exploring the domain models that stakeholders use. *Discovering these domain models can be valuable even if you don't end up writing any code*.
* There is a circular dependency between BDD and DDD - *we can't have behaviour driven conversations without DDD and BDD helps structure the conversations you can have in DDD*. The structure that the Given, When, Then scenarios provide for having conversations was also identified as being a key part of how BDD can be useful. When it comes to coding, DDD helps drive the design and BDD helps drive what you develop.
