+++
draft = false
date="2017-03-30 22:38:47"
title="My top 10 technology podcasts"
tag=['software-development', 'podcasts']
category=['Software Development']
description="A collection of my favourite technology podcasts covering data science, data engineering, bitcoin, Kubernetes, software development, and more."
+++

For the last six months I&#8217;ve been listening to 2 or 3 technology podcasts every day while out running and on my commute and I thought it&#8217;d be cool to share some of my favourites.

I listen to all of these on the https://www.podbean.com/[Podbean] android app which seems pretty good. It can&#8217;t read the RSS feeds of some podcasts but other than that it&#8217;s worked well.

Anyway, on with the podcasts:

[#__a_href_https_softwareengineeringdaily_com_category_podcast_software_engineering_daily_a]
== https://softwareengineeringdaily.com/category/podcast/[Software Engineering Daily]

This is the most reliable of all the podcasts I&#8217;ve listened to and a new episode is posted every weekday.

It sweeps across lots of different areas of technology - there&#8217;s a bit of software development, a bit of data engineering, and a bit of infrastructure.

Every now and then there&#8217;s a focus on a particular topic area or company which I find really interesting e.g. in 2015 there was a week of https://softwareengineeringdaily.com/tag/bitcoin/[Bitcoin focused episodes] and more recently there&#8217;s been a https://softwareengineeringdaily.com/tag/stripe/[bunch of episodes about Stripe].

[#__a_href_http_partiallyderivative_com_partially_derivative_a]
== http://partiallyderivative.com/[Partially Derivative]

This one is more of a data science postcast and cover lots of different areas in that space but thankfully keep the conversation at a level that a non data scientist like me can understand.

I especially liked the http://partiallyderivative.com/podcast/2016/11/14/decision-boundary-2016-margin-of-terror[post US election episode] where they talked about the problems with polling and how most election predictions had ended up being wrong.

There&#8217;s roughly one new episode a week.

[#__a_href_https_www_oreilly_com_topics_oreilly_bots_podcast_o_reilly_bots_podcast_a]
== https://www.oreilly.com/topics/oreilly-bots-podcast[O&#8217;Reilly Bots podcast]

I didn&#8217;t know anything about bots before i listened to this podcast and it was quite addictive - i powered through all the episodes in a few weeks.

They cover all sorts of topics that I&#8217;d have never thought of - why have developers got interested in bots? How do UIs differ to ones in apps? How do users find out about bots?

I really enjoy listening to this one but it&#8217;s been a bit quiet recently.

[#__a_href_http_packetpushers_net_series_datanauts_podcast_datanauts_a]
== http://packetpushers.net/series/datanauts-podcast/[Datanauts]

I found this one really useful for getting the hang of infrastructure topics. I wanted to learn a bit more about Kubernetes a few months ago and they had an episode which gives an overview as well as more detailed episodes.

One neat feature of this podcast is that after each part of an interview the hosts summarise what they picked up from that segment. I like that it gives you a few seconds to think about what you picked up and whether it matches the summary.

Some of the episodes go really deep into specific infrastructure topics and I struggle to follow along but there are enough other ones to keep me happy.

[#__a_href_https_www_becomingadatascientist_com_category_podcast_becoming_a_data_scientist_a]
== https://www.becomingadatascientist.com/category/podcast/[Becoming a Data Scientist]

This one mirrors the journey of https://twitter.com/BecomingDataSci[Renee Teate] getting into data science and bringing everyone along on the journey.

Each episode is paired with a learning exercises for the listener to try and although any of the learning exercises yet I like how some interviews are structured around them. e.g. https://www.becomingadatascientist.com/2016/03/28/becoming-a-data-scientist-podcast-episode-08-sebastian-raschka/[Sebastien Rashka was interviewed about model accuracy] on the week that was being explored in the learning club.

If you&#8217;re interested in data science topics but aren&#8217;t a data scientist yourself this is a good one to listen to.

[#__a_href_https_twimlai_com_this_week_in_machine_learning_and_ai_podcast_a]
== https://twimlai.com/[This Week In Machine Learning and AI Podcast]

This one mostly goes well over my head but it&#8217;s still interesting to listen to other people talk about stuff they&#8217;re working on.

There&#8217;s a lot of focus on Deep Learning so i think i need to learn a bit more about that and then the episodes will make more sense.

The https://twimlai.com/machine-learning-cybersecurity-evan-wright/[last episode with Evan Wright] was much more accessible. I need more like that one!

[#__a_href_https_thewomenintechshow_com_the_women_in_tech_show_a]
== https://thewomenintechshow.com/[The Women in Tech Show]

I came across https://twitter.com/edaenas[Edaena Salinas] on Software Engineering Daily and didn&#8217;t initially realise that Edaena had a podcast until a couple of weeks ago.

There&#8217;s lots of interesting content on this one. The episodes on https://thewomenintechshow.com/2017/01/30/data-driven-marketing-with-jessica-jobes/[data driven marketing] and https://thewomenintechshow.com/2016/12/13/unconscious-bias-in-hiring-with-stephanie-lampkin/[unconscious bias] are my favourites of the ones I&#8217;ve listened to so far.

[#__a_href_http_thebitcoinpodcast_com_the_bitcoin_podcast_a]
== http://thebitcoinpodcast.com/[The Bitcoin Podcast]

I listened to a few shows about bitcoin on Software Engineering Daily and found this podcast while trying to learn more.

Some of the episodes are general enough that i can follow along but others use a lot of block chain specific terminology that leave me feeling a bit lost.

I especially liked the http://thebitcoinpodcast.com/episode-118/[episode that featured Greg Walker] of http://learnmeabitcoin.com[learnmeabitcoin] fame. Greg uses Neo4j as part of the website and https://www.meetup.com/graphdb-london/events/237954465/[presented at the London Neo4j meetup earlier this week].

[#__a_href_https_changelog_com_gotime_go_time_a]
== https://changelog.com/gotime[Go Time]

This one has a chat based format that I really. They have a cool section called 'free software Friday' at the end of each show where everybody calls out a piece of software or maintainer that they&#8217;re grateful for.

I was playing around with Go in November/December last year so it was really helpful in pointing me in the right direction. I haven&#8217;t done any stuff recently so it&#8217;s more a general interest show for now.

[#__a_href_https_changelog_com_change_log_a]
== https://changelog.com/[Change Log]

This one covers lots of different topics, mostly around different open source projects.

The really cool thing about this one is they get every guest to explain their 'origin story' i.e. how did they get into software and what was their path to the current job. The https://changelog.com/podcast/241[interview with Nathan Sobo about Atom] was particularly good in this respect.

It&#8217;s always interesting to hear how other people got started and contrast it with my own experiences.

Another cool feature of this podcast is that they sometimes have episodes where they https://changelog.com/podcast/238[interview people at open source conferences].

[#_that_s_it_folks]
== That&#8217;s it folks

That&#8217;s all for now. Hopefully there&#8217;s one or more in there that you haven&#8217;t listened to before.

If you&#8217;ve got any suggestions for other ones I should listen to let me know in the comments or send me a message on twitter https://twitter.com/markhneedham[@markhneedham]
