+++
draft = false
date="2023-05-16 02:44:37"
title="GitHub: Get a CSV containing my pull requests (PRs)"
tag=['github', 'til']
category=['TIL']
description="In this post we'll learn how to get a list of our latest PRs using the GitHub CLI tool."
image="uploads/2023/05/ffmpeg-banner.png"
+++

:icons: font

I needed to crop a video that I used as part of a video on my YouTube channel, https://www.youtube.com/shorts/7950UzRDZBE[Learn Data With Mark^], and Camtasia kept rendering a black screen. 
So I had to call for FFMPEG!

My initial video was 2160 x 3840 but I didn't need the bottom 1920 pixels because I'm using that part of the screen for a video of me.
If I was just rendering that video exactly as it is I wouldn't have bothered cropping it, but because I wanted to zoom into different sections I needed to crop out the bottom bit.

I adapted an example from https://ottverse.com/crop-a-video-with-ffmpeg-crop-filter/[this article from OTTVerse^] as my first cut:

[source, bash]
----
gh search prs  \
--author=@me \
--limit 100 \
--json title,repository,closedAt,url | 
jq -r '.[]| [.title, .url, .repository.nameWithOwner, .closedAt] | @csv'
----
