+++
draft = false
date="2012-01-03 01:48:42"
title="My Software Development journey: 2011"
tag=['software-development']
category=['Software Development']
+++

A http://www.markhneedham.com/blog/2009/10/05/my-software-development-journey-year-3-4/[couple of years ago] I http://www.markhneedham.com/blog/2008/09/01/my-software-development-journey-so-far/[used to write a blog post] reflecting on what I'd worked on in the preceding year and what I'd learned and having read 2011 http://blog.fogus.me/2011/12/31/the-best-things-and-stuff-of-2011/[reviews by a couple] http://sermoa.wordpress.com/2011/12/31/aimees-2011-retrospective-a-year-in-review/[of other] http://lucisferre.net/2011/12/31/2012-year-in-review/?utm_campaign=829&utm_medium=twitter&utm_source=twitter[people] I thought I'd have a go.

== Am I actually learning anything?

A thought I had many times in 2011 was '*am I actually learning anything?*' as, although I was working with languages that I hadn't used professionally before, the applications that we I worked on were very similar to ones that I've worked on previously.

Often I'd work on something and know exactly how it should be designed and where we could go wrong since I'd done the same thing several times before and the challenge of not knowing what to do had disappeared somewhat.

== Now and then\...

I certainly failed to http://www.markhneedham.com/blog/2009/10/03/learn-one-thing-a-day/[learn one thing a day] as I suggested in a blog post a couple of years ago although eventually I managed to learn a bit about node.js and clojure by http://www.markhneedham.com/blog/2011/11/30/xp-day-visualizing-whats-happening-on-our-project/[building some toy applications] with my colleague https://twitter.com/#!/uday_rayala[Uday].

We decided to rewrite part of our Scala application in clojure in our own time to see what it'd look like which provided us with an interesting insight into what it'd be like to build a system for the second time when you know exactly what to do.

I also completed http://www.ml-class.org/course/class/index[ml-class] which was fun as it was the type of programming that I've never done before. Obviously I'm still a novice at the whole machine learning thing but it's given me an idea of the sorts of things you can do.

== Learning is doing

From February until April I was in Bangalore working as a trainer/coach for one of the http://www.markhneedham.com/blog/category/thoughtworks-university-2/[ThoughtWorks University] batches where we tried as much as possible to reduce the amount of 'teaching' done.

Sumeet has previously written about http://www.learninggeneralist.com/2010/08/thoughtworks-university-story-of-our.html[the new style of ThoughtWorks University] which is more focused on people working on a real project than sitting in workshops and we tried to take this even further.

Previous groups had spent about 2 weeks doing workshop style sessions and then 4 weeks working on a project but we got it to the point where we spent just over a week in workshops and the rest working on the project.

In general I think it worked reasonably well and the skill level of the group seemed reasonably high by the end. We were lucky that there were only 13 people in the group - it would be interesting to see how our approach would scale.

I've also noticed this last year that when I'm learning something new it's not enough to just do toy exercises anymore, *I actually have to build something to retain interest*.

During the Christmas holidays I decided to try and build a Flipboard style application for my Android phone so I can (yet again) capture the links that people post on twitter.

Actually having a real problem to solve has made me http://www.markhneedham.com/blog/category/android-2/[much more engaged] than following a tutorial or hello world demo would have done.

== Remembering the value of blogging

My rate of posting on here has decreased a lot over the last year which I think is partly down to the fact that I've written about a lot of the stuff I see on projects before but also because I started filtering what I thought was interesting enough to write about.

In hindsight the latter approach doesn't necessarily make sense - the most read posts on this blog are the ones which I thought were the most pointless when I wrote them.

I got stuck in the mindsight that I wasn't actually learning anything by writing blog posts, which has been proved wrong multiple times both in terms of what I learn in writing the post and from what I learn from people's comments.

== Expressing opinions in big groups/public

I spent 10 months in late 2010/early 2011 http://www.markhneedham.com/blog/category/distributed-agile/[working in India] and one of the most interesting things I remember observing was that people seemed very reluctant to express their opinion in big groups.

I thought that was something specific to India but on coming back to the UK I've noticed the same thing here as well which means we need to http://www.markhneedham.com/blog/2011/03/20/retrospectives-mini-group-discussions/[adjust our approach in retrospectives] if we want everyone to participate.

I also learnt that expressing strong opinions in public in isn't necessarily the most effective way of making change happen. I probably should have learnt this already but it became increasingly evident how ineffective this approach was in 2011.

== Going at my own pace

A couple of years ago I was advised by a couple of colleagues that the way to get to the 'next level' was to become more knowledgeable about the overall architectural design of systems but at the time I wasn't that interested in that.

It's only more recently that I've found it interesting to read about different architectures on http://highscalability.com/[High Scalability] or http://www.systemswemake.com/[Systems We Make].

Another interesting way for me to learn in this area is to try and understand the architectures used in other ThoughtWorks projects that I didn't work on and see how they compare to the ones I've worked on.

I generally can't force myself to be interested in something if I'm not but once I am interested then I want to learn every detail about it so it's better to wait until I become interested naturally.

The next thing which I'm sure I'll eventually become interested in is tech leading a team which several of my peers (in terms of years of experience) are doing now or have been doing for a year or two. Right now though I want to focus on coding!

== Overall\...

I'm not sure 2011 was a year where I learned as much as I did in previous years - the learning did seem to taper off a bit which in a way is inevitable unless you completely change your role/the types of things you're building.

In 2012 I plan to keep learning about Android development and I'm going to be doing http://www.algo-class.org/[algo-class] to try and get better at another aspect of programming which I'm not very good at right now.
