+++
draft = false
date="2011-06-18 18:45:29"
title="Chef, Fedora and 'ArgumentError: Attribute domain is not defined!'"
tag=['chef', 'fedora']
category=['DevOps']
+++

I've been playing around with http://wiki.opscode.com/display/chef/Chef+Solo[Chef Solo] on Fedora and executing the following:

[source,text]
----

sudo chef-solo -c config/solo.rb -j config/node.json
----

(where +++<cite>+++node.json+++</cite>+++ just contains the example code from the http://wiki.opscode.com/display/chef/Chef+Solo[resolver example on the Chef documentation page] and the cookbooks folder contains https://github.com/opscode/cookbooks/tree/master[all the opscode cookbooks].)

leads to the following error:

[source,text]
----

...
ERROR: Running exception handlers
ERROR: Exception handlers complete
FATAL: Stacktrace dumped to /home/mark/chef-solo/chef-stacktrace.out
FATAL: ArgumentError: Attribute domain is not defined!
----

A bit of googling led me to believe that this error is happening because http://lists.opscode.com/sympa/arc/chef/2010-03/msg00075.html[the machine doesn't have a fully qualified domain name (fqdn) defined] which can be seen by calling the following command:

[source,text]
----

$ hostname -f
> hostname: Name of service not known
----

One way to fix it is to add the following entry to +++<cite>+++/etc/hosts</etc>+++</cite>+++

[source,text]
----

127.0.0.1	mark-fedora
----

Which results in the script running fine with no errors.

[source,text]
----

...
INFO: Running report handlers
INFO: Report handlers complete
----

A suggestion I read while googling about fqdn was to add the hostname of the machine into a file called +++<cite>+++/etc/HOSTNAME+++</cite>+++ but that didn't seem to have any impact for me.

On the Mac +++<cite>+++hostname -f+++</cite>+++ works fine even without an entry like the above in +++<cite>+++/etc/hosts+++</cite>+++ so I'm not entirely sure how it all works!

If anyone could explain it to me that'd be awesome.
