+++
draft = false
date="2014-05-31 00:03:48"
title="Clojure: Destructuring group-by's output"
tag=['clojure']
category=['Clojure']
+++

One of my favourite features of Clojure is that it allows you to destructure a data structure into values that are a bit easier to work with.

I often find myself referring to http://blog.jayfields.com/2010/07/clojure-destructuring.html[Jay Fields' article] which contains several examples showing the syntax and is a good starting point.

One recent use of destructuring I had was where I was working with a vector containing events like this:

[source,lisp]
----

user> (def events [{:name "e1" :timestamp 123} {:name "e2" :timestamp 456} {:name "e3" :timestamp 789}])
----

I wanted to split the events in two - those containing events with a timestamp greater than 123 and those less than or equal to 123.

After remembering that the function I wanted was +++<cite>+++http://clojuredocs.org/clojure_core/1.2.0/clojure.core/group-by[group-by]+++</cite>+++ and not +++<cite>+++http://clojuredocs.org/clojure_core/1.2.0/clojure.core/partition-by[partition-by]+++</cite>+++ (I always make that mistake!) I had the following:

[source,lisp]
----

user> (group-by #(> (->> % :timestamp) 123) events)
{false [{:name "e1", :timestamp 123}], true [{:name "e2", :timestamp 456} {:name "e3", :timestamp 789}]}
----

I wanted to get 2 vectors that I could pass to the web page and this is fairly easy with destructuring:

[source,lisp]
----

user> (let [{upcoming true past false} (group-by #(> (->> % :timestamp) 123) events)]
       (println upcoming) (println past))
[{:name e2, :timestamp 456} {:name e3, :timestamp 789}]
[{:name e1, :timestamp 123}]
nil
----

Simple!
