+++
draft = false
date="2013-03-21 22:39:02"
title="Wiring up an Amazon S3 bucket to a CNAME entry - The specified bucket does not exist"
tag=['software-development', 'aws']
category=['Software Development']
+++

https://twitter.com/jasonneylon[Jason] and I were setting up an internal static website using an http://aws.amazon.com/s3/[S3] bucket a couple of days ago and wanted to point a more friendly domain name at it.

We initially called our bucket 'static-site' and then created a http://en.wikipedia.org/wiki/CNAME_record[CNAME] entry using http://www.zerigo.com/[zerigo] to point our sub domain at the bucket.

The mapping was something like this:

[source,text]
----

our-subdomain.somedomain.com -> static-site.s3-website-eu-west-1.amazonaws.com
----

When we tried to access the site through our-subdomain.somedomain.com we got the following error:

[source,text]
----

<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName></BucketName>
<RequestId></RequestId>
<HostId>
----

A bit of googling led us to https://forums.aws.amazon.com/message.jspa?messageID=237562[this thread] which suggested that we needed to ensure that our bucket was named after the sub domain that we wanted to serve the site from.

In this case we needed to rename our bucket to 'our-subdomain.somedomain.com" and then our CNAME entry to:

[source,text]
----

our-subdomain.somedomain.com -> our-subdomain.somedomain.com.s3-website-eu-west-1.amazonaws.com
----

And then everything was happy.
