+++
draft = true
date="2023-08-21 00:44:37"
title="pyarrow: pyarrow.lib.ArrowNotImplementedError: Filter argument must be boolean type"
tag=['python', 'pyarrow', 'til']
category=['TIL']
description="In this post, we'll learn how to add execution time to cells in JupyterLab."
image="uploads/2023/07/jupyterlab-banner.png"
+++

:icons: font

[source, python]
----
import pyarrow as pa

my_table = pa.Table.from_arrays(
    [pa.array(['foo', 'bar', 'foo'], pa.string())],
    names=['col1']
)
----

>>> arrow_table.filter("Region = 'NEAR EAST'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 3154, in pyarrow.lib.Table.filter
  File "/Users/markhneedham/Library/Caches/pypoetry/virtualenvs/ch07-YVG4Qrie-py3.11/lib/python3.11/site-packages/pyarrow/compute.py", line 259, in wrapper
    return func.call(args, options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 367, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Filter argument must be boolean type

[soruce, python]
----
import pyarrow.compute as pc
arrow_table = population_table.to_arrow()

arrow_table.filter(pc.equal(arrow_table["Region"], "NEAR EAST"))
# or
arrow_table.filter(pc.field("Region") == "NEAR EAST")
----