+++
draft = false
date="2012-12-30 22:39:16"
title="Haskell: Pattern matching a list"
tag=['haskell']
category=['Haskell']
+++

As I mentioned http://www.markhneedham.com/blog/2012/12/29/haskell-initialising-a-map/[in a post yesterday] I've been converting a clustering algorithm into Haskell and I wanted to get the value from doing a bit wise or on two values in a list.

I forgot it was possible to pattern match on lists until I http://www.markhneedham.com/blog/2012/04/15/haskell-a-simple-parsing-example-using-pattern-matching/[came across a post I wrote about 8 months ago] where I'd done this so my initial code looked like this:

[source,haskell]
----

> import Data.Bits
> map (\pair -> (pair !! 0) .|. (pair !! 1)) [[1,2], [3,4]]
[3,7]
----

We can pattern match against the list like so:

[source,haskell]
----

> map (\(x:y:_) -> x .|. y) [[1,2], [3,4]]
[3,7]
----

Here +++<cite>+++x+++</cite>+++ takes the first value, +++<cite>+++y+++</cite>+++ takes the second value and the rest of the list is assigned to +++<cite>+++_+++</cite>+++ which we don't use in this case.

There are loads of examples of pattern matching against different data structures in http://learnyouahaskell.com/syntax-in-functions[Learn You A Haskell] and hopefully next time I'll remember and won't write hideous code like the first example!
