+++
draft = false
date="2023-06-20 02:44:37"
title="DuckDB/SQL: Convert string in YYYYmmdd format to Date"
tag=['duckdb', 'til']
category=['TIL']
description="In this post we'll learn how to convert a date string to a Date type in DuckDB."
image="uploads/2023/06/duckdb-date-banner.png"
+++

I've been working with a data set that represents dates as strings in the format 'YYYYmmdd' and I wanted to convert those values to Dates in DuckDB.
In this blog post, we'll learn how to do that.

Let's create a small table with a single column that represents date of births:

[source, sql]
----
create table players (dob VARCHAR);
insert into players values('20080203');
----

We can write the following query to return the single row in the table:

[source, sql]
----
select * from players;
----

.Output
[%header,format=csv]
|===
dob
20080203
|===

At the moment the date of birth is a string, but we can use the `strptime` function to convert it to a timestamp:

[source, sql]
----
SELECT strptime(dob, '%Y%m%d') AS dob
FROM players;
----

.Output
[%header,format=csv]
|===
dob
"2008-02-03 00:00:00"
|===

I don't really care about the time component though, so let's get rid of that by casting it to a `DATE`:

[source, sql]
----
SELECT cast(strptime(dob, '%Y%m%d') AS DATE) AS dob
FROM players;
----

.Output
[%header,format=csv]
|===
dob
2008-02-03
|===
