languageCode = "en-us"
title = "Mark Needham"
baseurl = "https://www.markhneedham.com/blog/"
#baseurl = "http://localhost:8000/blog/"
theme = "hugo-theme-crisp"

[Params]
  Author = "Mark Needham"
  disqusShortname = "markhneedham12345"
  disqus = "markhneedham"
  twitter = "markhneedham"
  gplus = "100354797468725665406"
  ga = "UA-9991626-1"

[taxonomies]
  tag = "tag"
  category = "category"
