languageCode = "en-us"
title = "Mark Needham"
baseurl = "http://markhneedham.com/blog/"
# baseurl = "http://localhost:8000/"
theme = "hugo-theme-crisp"

[Params]
  Author = "Mark Needham"
  disqusShortname = "markhneedham12345"
  disqus = "markhneedham"
  twitter = "markhneedham"
  gplus = "100354797468725665406"
  ga = "9991626"

[taxonomies]
  tag = "tag"
  category = "category"
