languageCode = "en-us"
title = "Mark Needham"
baseurl = "https://mneedham.github.io/blog/"
theme = "hugo-theme-crisp"

[Params]
  Author = "Mark Needham"
  disqusShortname = "markhneedham12345"
  disqus = "markhneedham12345"
  twitter = "markhneedham"
  gplus = "100354797468725665406"
  ga = "9991626"

[taxonomies]
  tag = "tag"
  category = "category"
