+++
draft = true
date="2021-04-16 00:44:37"
title="Exploring England's Covid Vaccination Rates: The Data (cleanup)"
tag=['python', 'pandas', 'covid-vaccines', 'altair']
category=['python']
description="In this post we'll learn how to extract data about England's Covid vaccinations"
+++

Over the last 13 months I've spent countless hours looking at dashboards that showed Coronavirus infection rates, death rates, and numbers of people vaccinated.


[source,bash]
----
pip install pandas xlrd openpyxl altair
----

== The Data 

In a spreadsheet that Public Health England publish every Thursday - https://www.england.nhs.uk/statistics/statistical-work-areas/covid-19-vaccinations/

We need data that shows the number of people vaccinated in each area as well as an estimate of how many people live in that area. 
The spreadsheet refers to Local Tier Local Authorities, which I think are the same as local councils. 

LTLA and Population estimates (NIMS) sheets contain the data that we need. 
We'll have to join those two together. 

Preview of the spreadsheets 

(add the medium zoom library so it's easier to see)

== Reading the data

Loading the two sheets into Pandas and joining them together

We can use Pandas `read_excel` function to extract the data, but there is still a bit of clean up to do afterwards. 

[source, python]
----
import pandas as pd
import numpy as np
----

From visually inspecting the spreadsheet, we can see that columns B to M contain the data we're interested in. 
We can extract just those columns by using the `usecols` parameter, as shown below:

[source, python]
----
spreadsheet = "data/COVID-19-weekly-announced-vaccinations-15-April-2021.xlsx"
vaccinations = pd.read_excel(spreadsheet, "LTLA", usecols="B:M")
vaccinations.head()
----

.vaccinations DataFrame
[opts="header", cols="1,5,1,1,1,1,1,1,1,1,1,1"]
|===
| Unnamed: 1   | Unnamed: 2                                                                                                                                                                                                                                                                                                                 |   Unnamed: 3 |   Unnamed: 4 |   Unnamed: 5 |   Unnamed: 6 |   Unnamed: 7 |   Unnamed: 8 |   Unnamed: 9 |   Unnamed: 10 |   Unnamed: 11 |   Unnamed: 12 
| Title:       | COVID-19 Vaccinations By Lower Tier Local Authority (LTLA) of Residence and Age Group                                                                                                                                                                                                                                      |          nan |          nan |          nan |          nan |          nan |          nan |          nan |           nan |           nan |           nan 
| Summary:     | The number of people who have been vaccinated for COVID-19, split by LTLA of residence and age group. All figures are presented by date of vaccination as recorded on the National Immunisation Management Service (NIMS) database. NIMS vaccination counts and populations by LTLA are provided by Public Health England. |          nan |          nan |          nan |          nan |          nan |          nan |          nan |           nan |           nan |           nan 
| Period:      | 8th December 2020 to 11th April 2021                                                                                                                                                                                                                                                                                       |          nan |          nan |          nan |          nan |          nan |          nan |          nan |           nan |           nan |           nan 
| Source:      | National Immunisation Management Service (NIMS), Public Health England                                                                                                                                                                                                                                                     |          nan |          nan |          nan |          nan |          nan |          nan |          nan |           nan |           nan |           nan 
| Basis:       | England                                                                                                                                                                                                                                                                                                                    |          nan |          nan |          nan |          nan |          nan |          nan |          nan |           nan |           nan |           nan 
|===

We clearly still have some cleanup work to do.

[source,python]
----
vaccinations = pd.read_excel(spreadsheet, "LTLA", usecols="B:M")
columns = np.concatenate((vaccinations.loc[10,:][:4].values, vaccinations.loc[11,:][4:].values), axis=None)
vaccinations = vaccinations.loc[14:327,]
----

[source, python]
----
def vaccinations_dataframe(spreadsheet):
    vaccinations = pd.read_excel(spreadsheet, "LTLA", usecols="B:M")
    columns = np.concatenate((vaccinations.loc[10,:][:4].values, vaccinations.loc[11,:][4:].values), axis=None)
    vaccinations = vaccinations.loc[14:327,]
    vaccinations.columns = columns
    vaccinations = vaccinations.drop(["Region Code (Administrative)", "Region Name (administrative)"], axis=1)
    vaccinations = vaccinations.convert_dtypes()
    return vaccinations
----

== Visualising

Map of the country showing the areas shaded by % of people vaccinated
Bar charts showing 