+++
draft = false
date="2023-05-15 02:44:37"
title="Cropping a video using FFMPEG"
tag=['ffmpeg', 'til']
category=['TIL']
description="In this post we'll learn how to use the FFMPEG command line tool to crop part of a video."
image="uploads/2023/05/ffmpeg-banner.png"
+++

:icons: font

I needed to crop a video that I used as part of a video on my YouTube channel, https://www.youtube.com/shorts/7950UzRDZBE[Learn Data With Mark^], and Camtasia kept rendering a black screen. 
So I had to call for FFMPEG!

My initial video was 2160 x 3840 but I didn't need the bottom 1920 pixels because I'm using that part of the screen for a video of me.
If I was just rendering that video exactly as it is I wouldn't have bothered cropping it, but because I wanted to zoom into different sections I needed to crop out the bottom bit.

I adapted an example from https://ottverse.com/crop-a-video-with-ffmpeg-crop-filter/[this article from OTTVerse^] as my first cut:

[source, bash]
----
ffmpeg -i ConfigSegThresholdDemo.mp4 \
  -filter_complex "[0:v]crop=in_w:in_h-1920:0:0[cropped]" \
  -map "[cropped]" \
  -r output.mp4
----

This command tells FFMPEG to crop a region: 

* whose width is equal to the source video's width,
* whose height is equal to the source video's height minus 1920 pixels,
* and the origin is at [0,0]

This worked, but it lost the quality that I had in the initial video.
I fixed this by also passing the https://stackoverflow.com/questions/25569180/ffmpeg-convert-without-loss-quality[`qscale`^] flag:

[source, bash]
----
ffmpeg -i ConfigSegThresholdDemo.mp4 \
  -filter_complex "[0:v]crop=in_w:in_h-1920:0:0[cropped]" \
  -map "[cropped]" \
  -qscale 0 \
  -r output.mp4
----

I think it worked out pretty well, but https://youtube.com/shorts/7950UzRDZBE?feature=share[watch the video^] and let me know if you agree!