+++
draft = false
date="2009-12-09 22:10:27"
title="Haskell vs F#: Function composition"
tag=['f', 'haskell']
category=['F#']
+++

I'm reading through John Hughes' 'http://www.cs.chalmers.se/~rjmh/Papers/whyfp.html[Why functional programming matters]' paper and one thing I've come across which is a bit counter intuitive to me is the Haskell function composition operator.

I've http://www.markhneedham.com/blog/2009/01/12/f-partial-function-application-with-the-function-composition-operator/[written previously about F#'s function composition operator] which is defined as follows:

[source,ocaml]
----

let inline (>>) f g x = g(f x)
----

To write a function which doubled all the values in a list and then returned the odd values we'd do this:

[source,ocaml]
----

let doubleThenOdd = List.map (fun x -> x*2) >> List.filter (fun x -> x % 2 <> 0)
----

Of course it's not possible for there to be any values!

[source,text]
----

doubleThenOdd [1..5];;
val it : int list = []
----

Based on that understanding I would expect the Haskell function composition operator ('.') to work in the same way:

[source,haskell]
----

let doubleThenOdd = map (\ x -> x*2) . filter (\ x -> (mod x 2) /= 0)
----

But it doesn't!

[source,text]
----

Prelude> doubleThenOdd [1..5]
[2,6,10]
----

In Haskell the functions are applied from right to left rather than left to right as I had expected.

The definition of '.' is therefore:

[source,text]
----

(f . g) x = f (g x)
----

So to get what I wanted we'd need to switch around 'map' and 'filter':

[source,haskell]
----

let doubleThenOdd = filter (\ x -> (mod x 2) /= 0) . map (\ x -> x*2)
----

[source,text]
----

Prelude> doubleThenOdd [1..5]
[]
----

It's not too difficult to follow once I worked out that it was different to what I was used to but I was very confused for a while!

Is there a reason why they implement this operator differently?
