+++
draft = false
date="2017-12-03 17:23:14"
title="Python: Combinations of values on and off"
tag=['python', 'python3']
category=['Python']
+++

In my continued exploration of Kaggle's https://www.kaggle.com/c/spooky-author-identification/leaderboard[Spooky Authors competition], I wanted to run a http://scikit-learn.org/stable/modules/ensemble.html#using-the-votingclassifier-with-gridsearch[GridSearch] turning on and off different classifiers to work out the best combination.

I therefore needed to generate combinations of 1s and 0s enabling different classifiers.

e.g. if we had 3 classifiers we'd generate these combinations

[source,text]
----

0 0 1
0 1 0
1 0 0
1 1 0
1 0 1
0 1 1
1 1 1
----

where\...

* '0 0 1' means: classifier1 is disabled, classifier3 is disabled, classifier3 is enabled
* '0 1 0' means: classifier1 is disabled, classifier3 is enabled, classifier3 is disabled
* '1 1 0' means: classifier1 is enabled, classifier3 is enabled, classifier3 is disabled
* '1 1 1' means: classifier1 is enabled, classifier3 is enabled, classifier3 is enabled

\...and so on. In other words, we need to generate the binary representation for all the values from 1 to 2^number of classifiers^-1.

We can write the following code fragments to calculate a 3 bit representation of different numbers:

[source,python]
----

>>> "{0:0b}".format(1).zfill(3)
'001'
>>> "{0:0b}".format(5).zfill(3)
'101'
>>> "{0:0b}".format(6).zfill(3)
'110'
----

We need an array of 0s and 1s rather than a string, so let's use the +++<cite>+++list+++</cite>+++ function to create our array and then cast each value to an integer:

[source,python]
----

>>> [int(x) for x in list("{0:0b}".format(1).zfill(3))]
[0, 0, 1]
----

Finally we can wrap that code inside a list comprehension:

[source,python]
----

def combinations_on_off(num_classifiers):
    return [[int(x) for x in list("{0:0b}".format(i).zfill(num_classifiers))]
            for i in range(1, 2 ** num_classifiers)]
----

And let's check it works:

[source,python]
----

>>> for combination in combinations_on_off(3):
       print(combination)

[0, 0, 1]
[0, 1, 0]
[0, 1, 1]
[1, 0, 0]
[1, 0, 1]
[1, 1, 0]
[1, 1, 1]
----

what about if we have 4 classifiers?

[source,python]
----

>>> for combination in combinations_on_off(4):
       print(combination)

[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 0, 1, 1]
[0, 1, 0, 0]
[0, 1, 0, 1]
[0, 1, 1, 0]
[0, 1, 1, 1]
[1, 0, 0, 0]
[1, 0, 0, 1]
[1, 0, 1, 0]
[1, 0, 1, 1]
[1, 1, 0, 0]
[1, 1, 0, 1]
[1, 1, 1, 0]
[1, 1, 1, 1]
----

Perfect! We can now use this function to help work out which combinations of classifiers are needed.
