+++
draft = false
date="2010-04-22 23:35:27"
title="Haskell: parse error on input `='"
tag=['haskell']
category=['Haskell']
+++

I've been trying to follow the 'http://irekjozwiak.com/entry/2009/06/13/Monads-for-Java-C---programmers.html[Monads for Java/C++ programmers]' post in ghci and getting the following type of error when trying out the code snippets:

[source,haskell]
----

Prelude> a = 3

<interactive>:1:2: parse error on input `='
----

I figured there must be something wrong with my installation of the compiler since I was copying and pasting the example across and having this problem. Having reinstalled that, however, I still had the same problem.

I eventually came across http://greenokapi.net/blog/2007/02/19/chapter-1-of-hudaks-haskell-school-of-expression/[this blog post] which points to a http://ircarchive.info/haskell/2007/2/19/27.html[mailing list thread from a few years ago] where pjd explains that the 'let' construct is required when defining a variable from ghci and wouldn't necessarily be needed in a normal program:

____
*pjd* osfameron: about the ghci thing, you have to prefix definitions with "let" as in: let simple x y z = x * (y + z) *pjd* the reason for this is that ghci is in an implicit do block *pjd* so it's not exactly like top-level haskell
____

We have to use a 'let' in front of any variable/function definitions and then it will work as expected:

[source,haskell]
----

Prelude> let a = 3
3
----

http://book.realworldhaskell.org/read/getting-started.html[According to Real World Haskell]:

____
This syntax is ghci-specific The syntax for let that ghci accepts is not the same as we would use at the "`top level`" of a normal Haskell program.
____
