+++
draft = false
date="2008-08-20 18:50:18"
title="Building in release mode with no pdbs with msbuild"
tag=['build', 'msbuild', 'net', 'microsoft', 'release']
category=['.NET', 'Build']
+++

I've been having trouble trying to work out how to build our projects in msbuild in release mode without creating the customary http://msdn.microsoft.com/en-us/library/yd4f8bd1(VS.71).aspx[pdb] files that seem to be created by default.

I tried calling msbuild.exe with the 'Release' configuration:

[source,text]
----

'C:\WINDOWS\Microsoft.NET\Framework\v3.5\MSBuild.Exe ( Proj.csproj /p:OutputPath=\output\path\ 	/p:Configuration=Release)'
----

To no avail. It still created the pdb file. Next I tried setting the 'DebugSymbols' property to false:

[source,text]
----

'C:\WINDOWS\Microsoft.NET\Framework\v3.5\MSBuild.Exe ( Proj.csproj /p:OutputPath=\output\path\ 	/p:Configuration=Release /p:DebugSymbols=false)'
----

Still it created the file. Finally I found http://forums.msdn.microsoft.com/en-US/msbuild/thread/59d636b2-0cf3-4434-b7b9-c20f2e38fb18/[this post] which suggested that you actually needed to make the change in the Proj.csproj file itself.

I changed this part of the file so that DebugType is now 'none'. It had a value of 'pdbonly'  when I opened the file.

[source,text]
----

  none
  true
  bin\Release\
  TRACE
  prompt
  4
----

The pdb is no longer created.

_Update_
This can also be done by passing /p:DebugType=none as a command line argument as link:2008/08/20/building-in-release-mode-with-no-pdbs-with-msbuild/#comment-67[Tim points out] in the comments.
