+++
draft = false
date="2015-03-17 01:32:18"
title="One month of mini habits"
tag=['software-development']
category=['Software Development']
+++

I recently read a book in the 'getting things done' genre written by Stephen Guise titled 'http://www.amazon.co.uk/Mini-Habits-Smaller-Bigger-Results-ebook/dp/B00HGKNBDK[Mini Habits]' and although I generally don't like those types of books I quite enjoyed this one and decided to give his system a try.

The underlying idea is that there are two parts of actually doing stuff:

* Planning what to do
* Doing it

We often get stuck in between the first and second steps because what we've planned to do is too big and overwhelming.

Guise's approach for overcoming this inaction is to shrink the amount of work to do until it's *small enough that we don't feel any resistance to getting started*.

It should be something that you can do in 1 or 2 minutes - stupidly small - something that you can do even on your worst day when you have no time/energy.

I'm extremely good at procrastinating so I thought I'd give it a try and see if it helped. Guise suggests starting with one or two habits but I had four things that I want to do so I've ignored that advice for now.

My attempted habits are the following:

* Read one page of a data science related paper/article a day
* Read one page of a computer science related paper/article a day
* Write one line of data science related code a day
* Write 50 words on blog a day

== Sooooo\....has it helped?

In terms of doing each of the habits I've been successful so far - today is the 35th day in a row that I've managed to do each of them. Having said that, there have been some times when I've got back home at 11pm and realised that I haven't done 2 of the habits and need to quickly do the minimum to 'tick them off'.

The habit I've enjoyed doing the most is writing one line of data science related code a day.

My initial intention was that this was going to only involved writing machine learning code but at the moment I've made it a bit more generic so it can include things like the http://www.markhneedham.com/blog/2015/03/11/pythonneo4j-finding-interesting-computer-sciency-people-to-follow-on-twitter/[Twitter Graph] or other bits and pieces that I want to get started on.

The main problem I've had with making progress on mini projects like that is that I imagine its end state and it feels too daunting to start on. Committing to just one line of code a day has been liberating in some way.

One tweak I have made to all the habits is to have some rough goal of where all the daily habits are leading as I noticed that the stuff I was doing each day was becoming very random. https://twitter.com/mesirii[Michael] pointed me at Amy Hoy's 'http://files.alexpcoleman.com/newsletter/2014/04/The%2030x500%20Guide%20to%20Doing%20It%20Backwards.pdf[Guide to doing it backwards]' which describes a neat technique for working back from a goal and determining the small steps required to achieve it.

Writing at least 50 words a day has been beneficial for getting blog posts written. Before the last month I've found myself writing most of my posts at the end of month but I have a more regular cadence now which feels better.

Computer science wise I've been picking up papers which have some sort of link to databases to try and learn more of the low level detail there. e.g. I've read the http://www.cs.iit.edu/~yee/classes/cs525aut04/oneil93lruk.pdf[LRU-K cache] paper which Neo4j 2.2's page cache is based on and have been flicking through the original https://hal.archives-ouvertes.fr/inria-00555588/document[CRDTs] paper over the last few days.

I also recently came across the Papers We Love repository so I'll probably work through some of the https://github.com/papers-we-love/papers-we-love/tree/master/distributed_systems[distributed systems papers] they've collated next.

== Other observations

I've found that if I do stuff early in the morning it feels better as you know it's out of the way and doesn't linger over you for the rest of the day.

I sometimes find myself wanting to just tick off the habits for the day even when it might be interesting to spend more time on one of the habits. I'm not sure what to make of this really - perhaps I should reduce the number of habits to the ones I'm really interested in?

With the writing it does sometimes feel like I'm just writing for the sake of it but it is a good habit to get into as it forces me to explain what I'm working on and get ideas from other people so I'm going to keep doing it.

I've enjoyed my experience with 'mini habits' so far although I think I'd be better off focusing on fewer habits so that there's still enough time in the day to read/learn random spontaneous stuff that doesn't fit into these habits.
